spring.application.name=consumer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hiep
spring.rabbitmq.password=phuochiep

spring.rabbitmq.listener.simple.acknowledge-mode=manual

# Allow deserialization of all classes (temporary fix)
spring.amqp.deserialization.trust.all=true