spring.application.name=order-service
jwt.secret=inX25Mm6HCo4K8BsgUP51pdJONIyNdMIufpwQ0O2b6u404URP5ij5prIiH5mS4BJ/WczPO5f5uaRhqWeLUdhgg==
jwt.expiration=86400000

server.port=8083

server.servlet.context-path=/

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
